version: "3.7"

services:

  hblock-resolver:
    image: "hectormolinero/hblock-resolver:latest"
    restart: "on-failure:3"
    networks:
      - "hblock-resolver"
    dns:
      - "1.1.1.1"
      - "1.0.0.1"
    ports:
      - "127.0.0.153:53:53/udp"
      - "127.0.0.153:53:53/tcp"
      - "127.0.0.153:853:853/tcp"
    volumes:
      - "hblock-resolver-data:/var/lib/knot-resolver/"
      - "caddy-data:/var/lib/caddy/:ro"
    environment:
      KRESD_CERT_MANAGED: "false"
      KRESD_CERT_CRT_FILE: "/var/lib/caddy/acme/${TLS_CASERVER}/sites/${TLS_DOMAIN}/${TLS_DOMAIN}.crt"
      KRESD_CERT_KEY_FILE: "/var/lib/caddy/acme/${TLS_CASERVER}/sites/${TLS_DOMAIN}/${TLS_DOMAIN}.key"
    entrypoint: "/bin/sh"
    command: |
      -eu -c ' \
        until [ -f "$${KRESD_CERT_CRT_FILE:?}" ]; do echo "Waiting for Caddy..."; sleep 3; done;
        exec tini docker-foreground-cmd
      ;'
    depends_on:
      - "caddy"

  caddy:
    image: "hectormolinero/caddy:latest"
    restart: on-failure:3
    networks:
      - "hblock-resolver"
    dns:
      - "1.1.1.1"
      - "1.0.0.1"
    ports:
      - "127.0.0.153:443:443/tcp"
    volumes:
      - "./Caddyfile:/etc/caddy/Caddyfile:ro"
      - "caddy-data:/var/lib/caddy/"
    environment:
      TLS_DOMAIN: "${TLS_DOMAIN}"
      TLS_EMAIL: "${TLS_EMAIL}"
      TLS_CASERVER: "${TLS_CASERVER}"
      TLS_DNSPROVIDER: "${TLS_DNSPROVIDER}"
      CLOUDFLARE_EMAIL: "${CLOUDFLARE_EMAIL}"
      CLOUDFLARE_API_KEY: "${CLOUDFLARE_API_KEY}"

networks:

  hblock-resolver:

volumes:

  hblock-resolver-data:
  caddy-data:
