image: docker:stable

services:
  - docker:dind

stages:
  - build

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2

build:native-image:
  stage: build
  before_script:
    - apk add --no-cache coreutils m4 make
    - docker info
  script:
    - >
      make
      IMAGE_VERSION="${CI_COMMIT_REF_SLUG}"
      build-native-image
      save-native-image
  only:
    - branches
  artifacts:
    expire_in: 1 day
    paths:
      - dist/

build:cross-images:
  stage: build
  before_script:
    - apk add --no-cache coreutils m4 make
    - "mkdir -p ~/.docker/ && printf '%s\n' '{\"experimental\": \"enabled\"}' > ~/.docker/config.json"
    - docker login -u "${CI_DEPLOY_USER}" -p "${CI_DEPLOY_PASSWORD}" "${CI_REGISTRY}" >/dev/null 2>&1
    - docker info
  script:
    - >
      make
      IMAGE_VERSION="${CI_COMMIT_REF_SLUG}"
      binfmt-register
      build-cross-images
      save-cross-images
      push-cross-images
  only:
    - /^v([0-9.]+)(-.+)?$/
  except:
    - branches
  artifacts:
    expire_in: 1 week
    paths:
      - dist/
