version: "3.7"

services:

  caddy:
    image: "docker.io/hectormolinero/caddy:latest"
    restart: "on-failure:3"
    hostname: "caddy"
    networks:
      - "hblock-resolver"
    ports:
      - "127.0.0.153:80:80/tcp"
      - "127.0.0.153:443:443/tcp"
    volumes:
      - "./config/caddy/Caddyfile:/etc/caddy/Caddyfile:ro"
      - "caddy-data:/var/lib/caddy/"
    environment:
      TLS: "${TLS}"
      TLS_DOMAIN: "${TLS_DOMAIN}"
      TLS_EMAIL: "${TLS_EMAIL}"
      TLS_CASERVER: "${TLS_CASERVER}"
      TLS_DNSPROVIDER: "${TLS_DNSPROVIDER}"
      CLOUDFLARE_EMAIL: "${CLOUDFLARE_EMAIL}"
      CLOUDFLARE_API_KEY: "${CLOUDFLARE_API_KEY}"
    depends_on:
      - "hblock-resolver"
      - "grafana"

  hblock-resolver:
    image: "docker.io/hectormolinero/hblock-resolver:latest"
    restart: "on-failure:3"
    hostname: "hblock-resolver"
    networks:
      - "hblock-resolver"
    ports:
      - "127.0.0.153:53:53/udp"
      - "127.0.0.153:53:53/tcp"
      - "127.0.0.153:853:853/tcp"
    volumes:
      - "./config/kresd/graphite.conf:/etc/knot-resolver/kresd.conf.d/030-module-graphite.conf:ro"
      - "hblock-resolver-data:/var/lib/knot-resolver/"
      - "caddy-data:/var/lib/caddy/:ro"
    entrypoint: "/bin/sh"
    command: |
      -eu -c "
        if [ '${TLS}' = on ]; then
          export KRESD_CERT_MANAGED=false
          export KRESD_CERT_CRT_FILE=/var/lib/caddy/acme/${TLS_CASERVER:?}/sites/${TLS_DOMAIN:?}/${TLS_DOMAIN:?}.crt
          export KRESD_CERT_KEY_FILE=/var/lib/caddy/acme/${TLS_CASERVER:?}/sites/${TLS_DOMAIN:?}/${TLS_DOMAIN:?}.key
        fi
        exec tini container-foreground-cmd"
    depends_on:
      - "influxdb"

  grafana:
    image: "docker.io/grafana/grafana:latest"
    restart: "on-failure:3"
    hostname: "grafana"
    networks:
      - "hblock-resolver"
    volumes:
      - "./config/grafana/provisioning/:/etc/grafana/provisioning/:ro"
      - "grafana-data:/var/lib/grafana/"
    environment:
      GF_SERVER_ROOT_URL: "https://${TLS_DOMAIN}/grafana"
      GF_SERVER_SERVE_FROM_SUB_PATH: "true"
      GF_SECURITY_SECRET_KEY: "${GRAFANA_SECRET_KEY}"
      GF_SECURITY_ADMIN_PASSWORD: "${GRAFANA_ADMIN_PASSWORD}"
      GF_SECURITY_COOKIE_SECURE: "true"
      GF_INSTALL_PLUGINS: "grafana-piechart-panel,grafana-simple-json-datasource"
    depends_on:
      - "influxdb"

  influxdb:
    image: "docker.io/influxdb:latest"
    restart: "on-failure:3"
    hostname: "influxdb"
    networks:
      - "hblock-resolver"
    volumes:
      - "influxdb-data:/var/lib/influxdb/"
    environment:
      INFLUXDB_GRAPHITE_ENABLED: "true"
      INFLUXDB_GRAPHITE_DATABASE: "graphite"
      INFLUXDB_GRAPHITE_PROTOCOL: "udp"
      INFLUXDB_DATA_QUERY_LOG_ENABLED: "false"
      INFLUXDB_HTTP_LOG_ENABLED: "false"

networks:

  hblock-resolver:

volumes:

  caddy-data:
  hblock-resolver-data:
  grafana-data:
  influxdb-data:
