global:
  scrape_interval: "10s"
  scrape_timeout: "10s"

scrape_configs:
  - job_name: "prometheus"
    metrics_path: "/metrics"
    scheme: "https"
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ["hblock-resolver:8453"]
